package adminview;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import java.awt.HeadlessException;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author asd
 */
public class questionsguiupdate extends javax.swing.JInternalFrame {

    /**
     * Creates new form questionsgui
     */
    connection obj=new connection();
    public questionsguiupdate() {
        initComponents();
    display();
       
    }
    
    
     public void fromjtabletotextfields(){
        try{
    
    int row =jTable1.getSelectedRow();

qid.setText(jTable1.getModel().getValueAt(row,0).toString());
qstring_txt.setText(jTable1.getModel().getValueAt(row, 1).toString());
qcat_combo.setSelectedItem(jTable1.getModel().getValueAt(row,2).toString());
qopt1_txt.setText(jTable1.getModel().getValueAt(row, 3).toString());
qopt2_txt.setText(jTable1.getModel().getValueAt(row,4).toString());
qopt3_txt.setText(jTable1.getModel().getValueAt(row, 5).toString());
qopt4_txt.setText(jTable1.getModel().getValueAt(row,6).toString());
qcat_combo.setSelectedItem(jTable1.getModel().getValueAt(row,7).toString());
level_combo.setSelectedIndex((int) jTable1.getModel().getValueAt(row,8));

}

catch(Exception ex){
    JOptionPane.showMessageDialog(null, ex);
    
}
    }
    
    
    
    
    
    
    
    
    
    
    
    public void clearall(){
    qcat_combo.setSelectedItem("Select Category");
    qstring_txt.setText("");
    qopt1_txt.setText("");
    qopt2_txt.setText("");
    qopt3_txt.setText("");
    qopt4_txt.setText("");
    qid.setText("");
    level_combo.setSelectedIndex(0);
    answer.setSelectedItem("Choose Correct Answer");
}
    
    
    
    public boolean checkemptyfields(){
       boolean flag=false;
        if("Select Category".equals(qcat_combo.getSelectedItem())){
            JOptionPane.showMessageDialog(this, "Please Select category ");
        flag=false;
        }
        else if("".equals(qid.getText())){
        JOptionPane.showMessageDialog(this, "Enter Question Id ");
        flag=false;
    }
    else if("Choose Correct Answer".equals(answer.getSelectedItem())){
        JOptionPane.showMessageDialog(this, "Please Select Correct Answer ");
        flag=false;
    }
        else if("".equals(qstring_txt.getText())){
        JOptionPane.showMessageDialog(this, "Enter Question String ");
        flag=false;
    }
        else if("".equals(qopt1_txt.getText())){
        JOptionPane.showMessageDialog(this, "Enter Question Chioce 1 ");
        flag=false;
    }
        else if("".equals(qopt2_txt.getText())){
        JOptionPane.showMessageDialog(this, "Enter Question Chioce 2 ");
        flag=false;
    }
        else if("".equals(qopt3_txt.getText())){
        JOptionPane.showMessageDialog(this, "Enter Question Chioce 3 ");
        flag=false;
    }
        else if("".equals(qopt4_txt.getText())){
        JOptionPane.showMessageDialog(this, "Enter Question Chioce 4 ");
        flag=false;
    }
        else if("0".equals(level_combo.getSelectedItem())){
        JOptionPane.showMessageDialog(this, "Select Difficulty Level ");
        flag=false;
    }
        else{
          flag=true;
        }
        return flag;
    }
    
    public boolean checkemptyfordelete(){
       boolean flag=false;
        
         if("".equals(qid.getText())){
        JOptionPane.showMessageDialog(this, "Enter Question Id For DELETION ");
        flag=false;
    }
    
        else{
          flag=true;
        }
        return flag;
    }
    
    
    
    
    
    
    
    
    public void display() {
        
        obj.connect();
        ResultSet rs=obj.select("select * from questions");
        jTable1.setModel(DbUtils.resultSetToTableModel(rs));
       
        
    
    
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        qid = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        qstring_txt = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        qopt1_txt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        qopt2_txt = new javax.swing.JTextField();
        qopt3_txt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        qopt4_txt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        qcat_combo = new javax.swing.JComboBox<>();
        btn_update = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        level_combo = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        answer = new javax.swing.JComboBox<>();

        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("QUESTIONS FORM");

        jLabel2.setText("Question ID");

        jLabel3.setText("Question String");

        qstring_txt.setColumns(1);
        qstring_txt.setRows(2);
        jScrollPane1.setViewportView(qstring_txt);

        jLabel4.setText("Question Cateory");

        jLabel5.setText("Chioce 1");

        jLabel6.setText("Chioce 2");

        jLabel7.setText("Chioce 3");

        jLabel8.setText("Chioce 4");

        qcat_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Category" }));

        btn_update.setText("UPDATE");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jButton2.setText("DELETE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel9.setText("Difficulty Level");

        level_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", " " }));

        jLabel10.setText("Correct Answer");

        answer.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Correct Answer", "chioce 1", "chioce 2", "chioce 3", "chioce 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(41, 41, 41)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(37, 37, 37)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(qid, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(qcat_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btn_update, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(62, 62, 62))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 982, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(level_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(answer, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(qopt4_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(qopt3_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(qopt1_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE)
                                .addComponent(qopt2_txt)))))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(qid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(qcat_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_update, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(qopt1_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(qopt2_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(qopt3_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(qopt4_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(answer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(level_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
    
     questiondao obj2=new questiondao();
     questions obj1=new questions();
    
     try{
         
         boolean flag=checkemptyfields();
         if(flag == true){
         obj1.q_string=qstring_txt.getText();
         obj1.q_cat=qcat_combo.getSelectedItem().toString();
         obj1.q_opt1=qopt1_txt.getText();
         obj1.q_opt2=qopt2_txt.getText();
         obj1.q_opt3=qopt3_txt.getText();
         obj1.q_opt4=qopt4_txt.getText();
         obj1.q_id=Integer.parseInt(qid.getText());
         obj1.level=level_combo.getSelectedIndex();
         obj1.ans=answer.getSelectedItem().toString();
         obj2.updatequestions(obj1);
         JOptionPane.showMessageDialog(this,"Question Succesfully Updated");
         display();
         clearall();
         }
     
         
     }
     catch(HeadlessException ex ){
         JOptionPane.showMessageDialog(this, ex);
     }
     
    }//GEN-LAST:event_btn_updateActionPerformed

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated

        
        
      if(loginform.allowed==false){
           JOptionPane.showMessageDialog(this, "ACCESS DENIED .....Login First ");
           setVisible(false);
           dispose();
       }
         else{
            JOptionPane.showMessageDialog(this, "Welcome  "+ loginform.adminname);
            questiondao obj2=new questiondao();
try{
    

ResultSet rs=obj2.loadcombobox();
while(rs.next()){
    
    qcat_combo.addItem(rs.getString(1));
    
}

}

catch(SQLException ex){
        JOptionPane.showMessageDialog(null, ex);
        }
         }  
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        



// TODO add your handling code here:
    }//GEN-LAST:event_formInternalFrameActivated

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
  
        questiondao obj2=new questiondao();
     questions obj1=new questions();
    
     try{
         
         boolean flag=checkemptyfordelete();
         if(flag == true){
         
         obj1.q_id=Integer.parseInt(qid.getText());
         obj2.deletequestion(obj1);
         JOptionPane.showMessageDialog(this,"Question Deleted Succesfully");
         display();
         clearall();
         }
     
         
     }
     catch(HeadlessException ex ){
         JOptionPane.showMessageDialog(this, ex);
     }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
fromjtabletotextfields();        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> answer;
    private javax.swing.JButton btn_update;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> level_combo;
    private javax.swing.JComboBox<String> qcat_combo;
    private javax.swing.JTextField qid;
    private javax.swing.JTextField qopt1_txt;
    private javax.swing.JTextField qopt2_txt;
    private javax.swing.JTextField qopt3_txt;
    private javax.swing.JTextField qopt4_txt;
    private javax.swing.JTextArea qstring_txt;
    // End of variables declaration//GEN-END:variables

    private ResultSet displayquestions() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
